### ISSUE TITLE
Prototype and validate reason behind injecting baked README into crate-level docs comments

### ISSUE THREAD

**Issue by PsichiX** [RAUI-labs/raui#14]
possibly by writing proc macro that reads baked readme file and wraps it in `//!` comment lines inside `/src/lib.rs` files

**Comment by PsichiX** [comment]
i've just tried `#![doc = include_str!("../README.md")]` with nightly cargo doc and it injects readme into crate docs, but i'm not sure how to tel docs.rs to build docs using nightly 🤔

**Comment by zicklag** [comment]
The available Docs.rs options are listed [here](https://docs.rs/about/metadata), but I don't see anything that lets you specify the toolchain. Maybe they build on nightly by default? Lots of crates require nightly so it would make sense, especially when programs that compile on stable _should_ compile on nightly.

**Comment by zicklag** [comment]
Yep, they use nightly. Just found this:

ll crates are built in a sandbox using the nightly release of the Rust compiler. The current version in use is rustc 1.53.0-nightly (6df26f897 2021-04-20).

**Comment by PsichiX** [comment]
great, so we can turn actually implement this :D
