### ISSUE TITLE
Failing Website Build

### ISSUE THREAD

**Issue by zicklag** [RAUI-labs/raui#50]
https://github.com/RAUI-labs/raui/blob/8f765a2a8439822440a0b0be809ca97d49818b76/.github/workflows/website.yml#L33

The build is failing for the website and a quick look at the GitHub action, says that you have to create a personal access token and add it to your secrets to allow the site to deploy:

![image](https://user-images.githubusercontent.com/25393315/118043908-9b026580-b33b-11eb-986e-4fb7d0d4c5db.png)

**Comment by PsichiX** [comment]
ah, that's why! lemme make that one

**Comment by zicklag** [comment]
You should be able to re-run the build after setting the secret with this button when viewing the failed build.

![image](https://user-images.githubusercontent.com/25393315/118045406-7909e280-b33d-11eb-9d6e-ecdb164b5083.png)

**Comment by PsichiX** [comment]
hmm, is there an article about how to properly setup created secret to work with given repo? i'm having problems with the setup after i've created personal secret by following links in Zola readme 🤔

**Comment by zicklag** [comment]
Not that I know of. :thinking:

I think that you have to creat the token, and then go to the repo settings and add the token as a secret like this:

![image](https://user-images.githubusercontent.com/25393315/118047597-9a200280-b340-11eb-9012-aa6e460d95c2.png)


![image](https://user-images.githubusercontent.com/25393315/118047647-a906b500-b340-11eb-8d23-970eb9f6f8bb.png)

Also, we'll need to update the URL in the zola `config.toml` now that the repo org has changed and the URL will be different.

**Comment by PsichiX** [comment]
great! adding secret to repo and soon will push changes within config.toml

**Comment by PsichiX** [comment]
https://github.com/RAUI-labs/raui/runs/2570636086

i've ran `cargo fmt --all` after doing merge of local and remote `next` branch, but that should format only rust code - could that make this error? 🤔

**Comment by zicklag** [comment]
Oh, that's weird. I think it's trying to interpret the built zola site as a Jekyll site. We might need to add a `.nojekyll` file to the `site/static` folder to make sure that GitHub doesn't try to build the site as a Jekyll site.

**Comment by zicklag** [comment]
Ah yeah, here's the doc:

![image](https://user-images.githubusercontent.com/25393315/118049617-98a40980-b343-11eb-8ea2-3291b14c87bf.png)

**Comment by PsichiX** [comment]
i think that site/static wasn't the proper place for me to put that file into :D
what directory is the "root of publishing source"? 🤔

**Comment by zicklag** [comment]
It looks like that one worked: https://github.com/RAUI-labs/raui/actions/runs/837008605

**Comment by zicklag** [comment]
Oh, did you set GitHub pages to use the `gh-pages` branch to deploy?

**Comment by PsichiX** [comment]
probably 😅 i'm basically newbie when it comes to zola and GH pages :D

**Comment by zicklag** [comment]
![image](https://user-images.githubusercontent.com/25393315/118050419-d6556200-b344-11eb-871b-8fb7764fc007.png)

**Comment by zicklag** [comment]
That's what you should do.

**Comment by zicklag** [comment]
> probably sweat_smile i'm basically newbie when it comes to zola and GH pages :D

No problem. :D 

I'm new to Zola, too.

I think putting `.nojekyll` in the `static` did work, we just need to make sure that GitHub pages is using the `gh-pages` branch and not the `master` branch to deploy.

**Comment by PsichiX** [comment]
ok, so i've changed pages branch to gh-pages, also in last commit i've moved .nojekyll to `site/.nojekyll` but i don't see that change failed zola build so i think it can stay there.

i believe that i should re-run zola build again to make GH pages use gh-pages branch after change?

**Comment by PsichiX** [comment]
hmm, no, something is wrong again xD ok, i'll move back .nojekyll to static and re-run all jobs

**Comment by zicklag** [comment]
I think that will work. :)

**Comment by PsichiX** [comment]
YAY, we're live! :D :D :D

**Comment by zicklag** [comment]
It worked!!!! 🤯

Yay!

**Comment by PsichiX** [comment]
thanks for your great help with it <3

**Comment by zicklag** [comment]
Now we just need to update the repo link!

**Comment by PsichiX** [comment]
where? :O i thought i've fixed all places :O

**Comment by zicklag** [comment]
Glad I could help! It was good experience and I learned quite a bit from it. :)

**Comment by zicklag** [comment]
Just the one that pops up here:

![image](https://user-images.githubusercontent.com/25393315/118051462-aeff9480-b346-11eb-953c-57d96d8de62a.png)

**Comment by zicklag** [comment]
![image](https://user-images.githubusercontent.com/25393315/118051553-d48c9e00-b346-11eb-9068-2c5fb29e071e.png)

**Comment by PsichiX** [comment]
changed and added tags :D

**Comment by zicklag** [comment]
Perfect!
