### ISSUE TITLE
[Feature] Mechanism to Warn About Unimplemented Features

### ISSUE THREAD

**Issue by zicklag** [RAUI-labs/raui#53]
As I was working on extending the RAUI guide I ran into the fact that text alignment isn't implemented in the Tetra backend, but it doesn't give me any indication that it isn't implemented other than just not working. It would be good if we had some way to notify the user that they are using an unimplemented feature.

I see a couple of options:

- Panicking with `unimplemented!()`
- Using the `log` or `tracing` crates to log a `warn!`

I think that panicking isn't a good idea because it doesn't give the user a choice if they don't _care_ that it isn't implemented. For instance, say they wanted to run somebody elses RAUI UI and they didn't care that text wasn't aligned properly, they just wanted it to work as well as it could without.

The disadvantage to logging is an extra dependency? Seems like we might want logging anyway. The question then is whether or not we use the `log` crate or the `tracing` crate which is gaining a lot of traction lately.

**Comment by PsichiX** [comment]
i was thinking about it the other day and i'm definitely against enforcing certain logging crates (users might use others, that's gonna make using RAUI pinful, i've experienced same problems with when working on other projects).

my take would be: make a LogEngine that user plugs into the Application and it will handle passing RAUI log types (similar to Error types?) to the log engine and it's up to user or the plugin to log these warnings, with that we keep it pluggable and we allow users to quickly implement engines for their log crates.

**Comment by zicklag** [comment]
That sounds like a good idea. I think the log types would be more similar to log message types than error types. Each would probably be something like:

```rust
struct LogMessage {
    level: LogLevel,
    message: String,
    // This field might not be necessary. Not sure how useful it would be, it's just inspired by the `tracing`
    // concept of key=value pairs in log messages.
    data: HashMap<String, serde_json::Value>
}
```

**Comment by PsichiX** [comment]
hmm, do you have an example of where these logs might be useful and how we could access log engine there?

**Comment by zicklag** [comment]
The places that I think you'd run into the need to log a warning is mostly inside of the render implementation, so that you could warn about features RAUI has that maybe your renderer doesn't implement, like in the text-alignment example. That's the only situation that I've run into the need so far.

We could add the logger as an argument to the render function or something like that, or we could make the logger a `lazy_static` or something like that similar to the `log` crate so that it's accessible anywhere. :man_shrugging:

**Comment by PsichiX** [comment]
oh wait, so in that case i think we actually don't need log engine to be something "big", in a sense:
we could start with just a trait:
```rust
enum LogKind {
  Info,
  Warning,
  Error,
}

trait LogEngine {
  fn log(_kind: LogKind, _message: &str) {}
}

impl LogEngine for () {}
```
by that we establish common interface for all loggers to follow (we stay with log kind and message string without other parameters because honestly all what's logger does is just putting message in whatever text output, terminal, screen, file, etc.)

then in tetra renderer we just add public field for logger so user can add his own logger if he needs one:
```rust
pub struct TetraRenderer<'a, LE = ()> where LE: LogEngine {
    context: &'a mut Context,
    resources: &'a mut TetraResources,
    clip_stack: Vec<Rectangle<i32>>,
    pub logger: LE,
}
```
and that way only this renderer is gonna have logger and no other renderer. i would avoid enforcing logger in trait method argument if only tetra renderer is gonna make use of it.

**Comment by PsichiX** [comment]
i'm implementing support for loggers, gonna be on `next` soon.
