### ISSUE TITLE
Switch paper example

### ISSUE THREAD

**Issue by TuntematonSotilas** [RAUI-labs/raui#70]
Hello could you provide us a working example of the `switch_paper` component ?
It could be integrated into the existing demo

**Comment by PsichiX** [comment]
i believe i could upgrade in-game demo with more game focused UI examples (RPG games has nearly the most complex and most commonly used UI widgets)

**Comment by PsichiX** [comment]
ok, i've figured out how to make tabs component - gonna add that one to material library

**Comment by PsichiX** [comment]
i've started making examples for each of the component, switch and prolly tabs is gonna be published today :D

**Comment by PsichiX** [comment]
added examples for switch box and a couple of other core container components, pushed to `next` branch now, tomorrow i'll add interactive components and will push new version (i've improved raui-quick-start to allow use of callbacks within tetra context, and added support for passing process context to app builder).

along with RAUI new version i'll update RAUI in Oxygengine and push new version of it too tomorrow :)

**Comment by PsichiX** [comment]
i have finished adding examples for all core components, they are all on `next` branch (i had to wait with publishing new version until i got all of them covered)

**Comment by PsichiX** [comment]
also i've added a node variant called Tuple and its only purpose is to be able to make tuples of nodes that you should unpack in your component:
```rust
.listed_slot(WidgetNode::pack_tuple([
    make_widget!(image_box)
        .with_props(ImageBoxProps::colored(Color {
            r: 1.0,
            g: 0.25,
            b: 0.25,
            a: 1.0,
        }))
        .into(),
    make_widget!(image_box)
        .with_props(ImageBoxProps::colored(Color {
            r: 0.75,
            g: 0.25,
            b: 0.25,
            a: 1.0,
        }))
        .into(),
]))
```

i use it here to list pairs of tab-content items:
```rust
for (index, item) in listed_slots.into_iter().enumerate() {
        let [tab, content] = item.unpack_tuple();
}
```

**Comment by PsichiX** [comment]
hmm, actually i don't think i need to make a material/paper version of tabs_box because we user can just wrap tabs box in paper and that's all to do 🤔

**Comment by PsichiX** [comment]
ok, tabs box pushed to `next`, it's finally the time to publish new version. that was **a lot** of work :D

**Comment by zicklag** [comment]
Good job, man!

**Comment by PsichiX** [comment]
new version is now on crates and docs :D
