### ISSUE TITLE
Readme example doesn't work

### ISSUE THREAD

**Issue by Timmmm** [RAUI-labs/raui#78]
Firstly, this looks like a neat library! I like the idea.

Second, I tried the example from the README:

```
use raui::prelude::*;
use raui::renderer::json::JsonRenderer;
fn app(_: WidgetContext) -> WidgetNode { Default::default() }
fn title_bar(_: WidgetContext) -> WidgetNode { Default::default() }
fn text_button(_: WidgetContext) -> WidgetNode { Default::default() }

pub fn uimain() {
    // Coords mapping tell RAUI renderers how to convert coordinates
    // between virtual-space and ui-space.
    let mapping = CoordsMapping::new(Rect {
        left: 0.0,
        right: 1024.0,
        top: 0.0,
        bottom: 576.0,
    });

    // Application is UI host.
    let mut application = Application::default();
    // we use setup functions to register component and props mappings for serialization.
    application.setup(setup);
    // we can also register them at any time one by one.
    application.register_component("app", FnWidget::pointer(app));

    // Widget tree is simply a set of nested widget nodes.
    let tree = make_widget!(app)
        .named_slot("title", make_widget!(title_bar).with_props("Hello".to_owned())
        .named_slot("content", make_widget!(vertical_box)
            .listed_slot(make_widget!(text_button).key("hi").with_props("Say hi!".to_owned()))
            .listed_slot(make_widget!(text_button).key("exit").with_props("Exit!".to_owned()))
        )
    );

    // some dummy widget tree renderer.
    // it reads widget unit tree and transforms it into target format.
    let mut renderer = JsonRenderer::default();

    // `apply()` sets new widget tree.
    application.apply(tree);

    // `render()` calls renderer to perform transformations on processed application widget tree.
    if let Ok(output) = application.render::<JsonRenderer, String, _>(&mapping, &mut renderer) {
        println!("* OUTPUT:\n{}", output);
    }

    // by default application won't process widget tree if nothing was changed.
    // "change" is either any widget state change, or new message sent to any widget (messages
    // can be sent from application host, for example a mouse click, or from another widget).
    application.forced_process();
    if let Ok(output) = application.render::<JsonRenderer, String, _>(&mapping, &mut renderer) {
        println!("* OUTPUT:\n{}", output);
    }
}
```

However it just prints this:

```
* OUTPUT:
"None"
* OUTPUT:
"None"
```

That is presumably not expected?

**Comment by PsichiX** [comment]
thanks for the report - on it!

**Comment by PsichiX** [comment]
oh, ok i know where is the problem - you see the example actually shows only the pipeline part of RAUI, where widgets are uset empty ones producing nothing:
```rust
fn app(_: WidgetContext) -> WidgetNode { Default::default() }
fn title_bar(_: WidgetContext) -> WidgetNode { Default::default() }
fn text_button(_: WidgetContext) -> WidgetNode { Default::default() }
```
tho i think this causes misunderstanding, so i will create some content in these widgets and in the mean time please feel free to check out `examples` folder, because it shows the actual process.

**Comment by PsichiX** [comment]
ok, now widgets in hidden parts of readme snippets contain some content :)

**Comment by Timmmm** [comment]
Thanks, but I think you just added a load of `#`s? Am I being stupid?

https://github.com/RAUI-labs/raui/commit/5b4940770ef4e5293421a0ac34453f7c58dbc2c5

**Comment by Timmmm** [comment]
Ah wait, I found [the extra code](https://github.com/RAUI-labs/raui/commit/a8d6e8e42e71762020253bae673593e3e52de88b). Still not sure I understand the `#`s in the readme though?

**Comment by Timmmm** [comment]
Also I think this is wrong?

```
    // Widget tree is simply a set of nested widget nodes.
    let tree = make_widget!(app)
        .named_slot("title", make_widget!(title_bar).with_props("Hello".to_owned())
        .named_slot("content", make_widget!(vertical_box)
            .listed_slot(make_widget!(text_button).key("hi").with_props("Say hi!".to_owned()))
            .listed_slot(make_widget!(text_button).key("exit").with_props("Exit!".to_owned()))
        )
    );
```

Should be

```
    // Widget tree is simply a set of nested widget nodes.
    let tree = make_widget!(app)
        .named_slot("title", make_widget!(title_bar).with_props("Hello".to_owned()))
        .named_slot("content", make_widget!(vertical_box)
            .listed_slot(make_widget!(text_button).key("hi").with_props("Say hi!".to_owned()))
            .listed_slot(make_widget!(text_button).key("exit").with_props("Exit!".to_owned()))
        );
```

**Comment by PsichiX** [comment]
Weird bc what I wrote passes tests 🤔

**Comment by PsichiX** [comment]
I will have to take a look once again, I hope tests runner didn't broke

**Comment by PsichiX** [comment]
Anyway, in the mean time please take a look at examples folder, they show real life examples of usage, Readme snippets serves only as a way to show concepts, real life examples are in the examples folder

**Comment by PsichiX** [comment]
Oh I get, what I wrote is correct - you see, app widget has named slot "content" where we pass another widget, so parenthesis are fine there

**Comment by Timmmm** [comment]
With the existing code the "hi" and "exit" buttons do not appear in the output. With the change they do.

I was just using that code because it was the only example of using the JSON renderer, which was quite useful for figuring out how things work.

**Comment by PsichiX** [comment]
Ok, so tests passed bc I had working typo - thanks, I will fix that!

**Comment by PsichiX** [comment]
ok, i have pushed final readme snippet fixes (i hope 😅) - now it should work!

also, as we are on the topic of "which was quite useful for figuring out how things work" - what would be good thing for RAUI to have (other than working readme examples 😅) that would help figuring out how things works?

**Comment by PsichiX** [comment]
oh no, now i see what you meant by "bunch of #'s" - fixing that too!
